#Primer notebook para la capa bronze

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Rutas de los archivos

path_demo = "../data/raw/demo_asociados.csv"
path_ahorros = "../data/raw/Plano_ahorros.csv"
path_tx = "../data/raw/detalladoperaciones.csv"
path_interacciones = "../data/raw/publiturno.csv"
path_retiros = "../data/raw/Retiro_aportes_2022.csv"


# Lectura de archivos

df_demo = pd.read_csv(path_demo)
df_ahorros = pd.read_csv(path_ahorros)
df_tx = pd.read_csv(path_tx)
df_interacciones = pd.read_csv(path_interacciones)
df_retiros = pd.read_csv(path_retiros)

In [3]:
print(df_demo.shape)
print(df_ahorros.shape)
print(df_tx.shape)
print(df_interacciones.shape)
print(df_retiros.shape)

(248859, 8)
(50000, 5)
(50000, 4)
(50000, 5)
(66218, 10)

In [ ]:
#revisamos las primeras filas del dataframe de demo para entender su estructura
df_demo.head()

,Nit,Sexo,Fechnacimiento,Permanencia,Antasociado,Nivel_ingresos,Participacion_social,Uso_creditos
0,92657792,Masculino,1963-10-23 06:59:54,45,50,Medio,No,No
1,48525674,Femenino,1974-10-29 06:29:45,2,12,Alto,No,No
2,46537115,Masculino,1987-05-16 13:37:24,38,9,Medio,No,No
3,23875996,Masculino,1985-01-09 21:40:00,27,17,Bajo,Si,No
4,96840159,Femenino,1980-07-11 19:04:57,24,21,Bajo,No,No

In [6]:
# Revisar información general

df_demo.info()

<class 'pandas.DataFrame'>
RangeIndex: 248859 entries, 0 to 248858
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Nit                   248859 non-null  int64
 1   Sexo                  248859 non-null  str
 2   Fechnacimiento        248859 non-null  str
 3   Permanencia           248859 non-null  int64
 4   Antasociado           248859 non-null  int64
 5   Nivel_ingresos        248859 non-null  str
 6   Participacion_social  248859 non-null  str
 7   Uso_creditos          248859 non-null  str
dtypes: int64(3), str(5)
memory usage: 15.2 MB

In [7]:
# Revisar nulos

df_demo.isnull().sum()

Nit                     0
Sexo                    0
Fechnacimiento          0
Permanencia             0
Antasociado             0
Nivel_ingresos          0
Participacion_social    0
Uso_creditos            0
dtype: int64

In [9]:
# Revisar duplicados por Nit

df_demo["Nit"].duplicated().sum()

np.int64(344)

In [10]:
# Ver registros duplicados

duplicados_demo = df_demo[df_demo["Nit"].duplicated(keep=False)]

duplicados_demo.head(10)

,Nit,Sexo,Fechnacimiento,Permanencia,Antasociado,Nivel_ingresos,Participacion_social,Uso_creditos
108,98596200,Masculino,1993-05-18 13:43:33,35,14,Medio,Si,Si
556,84240254,Masculino,1973-07-09 18:17:53,9,35,Bajo,Si,No
1151,73906024,Masculino,1985-12-17 07:52:05,45,28,Alto,No,No
1583,62668515,Femenino,1964-09-22 15:23:39,40,10,Bajo,No,Si
1928,81278316,Masculino,2005-11-30 04:30:13,35,24,Medio,No,Si
3011,60831524,Masculino,1963-01-30 13:02:37,8,42,Bajo,Si,No
3293,88818248,Masculino,1999-10-01 11:01:47,5,39,Alto,No,No
3343,89468317,Masculino,1963-09-15 09:48:29,25,38,Medio,Si,No
4438,83921830,Masculino,1981-01-15 01:12:32,39,7,Medio,No,No
4805,46173879,Femenino,1993-02-20 23:41:14,46,33,Bajo,No,No

In [11]:
duplicados_demo.sort_values("Nit").head(20)

,Nit,Sexo,Fechnacimiento,Permanencia,Antasociado,Nivel_ingresos,Participacion_social,Uso_creditos
40429,10227174,Femenino,1969-01-15 01:04:55,49,17,Medio,No,No
154909,10227174,Femenino,1963-09-17 10:08:09,50,26,Bajo,No,Si
239404,10432759,Masculino,1997-02-07 17:34:17,47,5,Medio,No,No
79536,10432759,Masculino,1964-04-18 14:37:59,46,10,Alto,No,Si
140931,10438529,Masculino,1977-11-11 08:11:02,32,18,Medio,No,No
13150,10438529,Masculino,1960-03-31 18:01:33,5,29,Medio,No,No
80652,10908466,Masculino,1975-12-12 07:37:57,44,4,Bajo,Si,No
133071,10908466,Masculino,1985-02-15 13:37:45,49,44,Alto,No,Si
146079,10908995,Masculino,2001-03-23 06:26:11,36,44,Alto,Si,No
110435,10908995,Femenino,1995-12-23 11:34:21,22,50,Alto,No,No
88511,10918241,Femenino,1979-05-27 11:06:05,33,10,Medio,Si,Si
215690,10918241,Femenino,1993-06-02 17:40:19,4,20,Bajo,No,No
23142,11106909,Femenino,1961-11-11 12:56:05,1,22,Bajo,No,No
16321,11106909,Femenino,1969-10-25 16:17:08,50,8,Medio,No,Si
32613,11290579,Femenino,1991-05-31 03:39:59,32,4,Bajo,No,Si
175625,11290579,Masculino,1999-04-22 10:05:27,31,45,Bajo,Si,No
47029,11528362,Masculino,1995-09-03 04:13:00,22,34,Bajo,No,No
210360,11528362,Femenino,1968-03-28 05:59:11,34,43,Alto,No,No
109129,11774640,Masculino,1996-11-29 09:22:28,8,33,Medio,No,No
81761,11774640,Masculino,1959-04-02 06:07:35,23,29,Alto,Si,No